// Package testdatagarm supplies the declared taxonomy of the testdata proto
// package to the tests of [github.com/garm-ai/contracts/policy], and to
// garmd's, which import it across repositories.
//
// **Hand-written, and it must not be.** In the daemon's repository the
// equivalent is GENERATED by the tool plugin,
// and carries the service registry as well — Tools, Mount, RegisterTestService
// and a NATS client. All of that imports the enforcing package, which this
// repository must not depend on: the contract language compiles and validates
// declarations, and the runtime enforces them.
//
// The tests here only ever needed the taxonomy, so that is all this holds. The
// generated registry and the tests that exercise it belong beside the code
// they register into.
//
// What is left is a verification this repository cannot perform: the plugin
// that would emit this file is cmd/protoc-gen-garm-go, which stayed with the
// command line tool, so nothing here can tell you this is still byte-identical
// to what the plugin produces. The check belongs in the repository that has
// the plugin, comparing its output against this file. KNOWN-GAPS.md says so
// and names it as owed by garm rather than pending here.
package testdatagarm

import toolv1 "github.com/garm-ai/contracts/garm/tool/v1"

// Compartments is the taxonomy declared by testdata/fixture.proto, kept
// byte-identical to what the plugin emits for that file.
var Compartments = []*toolv1.Decl{
	{Name: "financial"},
	{Name: "pii-contact"},
	{Name: "support"},
}
